[build]
builder = "DOCKERFILE"
dockerfilePath = "back/Dockerfile"

[deploy]
startCommand = "cd back && npx prisma migrate deploy && npm start"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicy = "on-failure"
restartPolicyMaxRetries = 10

[deploy.env]
PORT = "3001"
NODE_ENV = "production"
NPM_CONFIG_PRODUCTION = "false" 