[build]
builder = "DOCKERFILE"
dockerfilePath = "elevatify-backend/Dockerfile"

[deploy]
startCommand = "cd elevatify-backend && npx prisma migrate deploy && npm start"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 10

[deploy.env]
PORT = "3001"
NODE_ENV = "production"
NPM_CONFIG_PRODUCTION = "false" 